### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by stephanvalentan** [jesg/dither-cxx#1]
Hello,
i'm working on a regression testing tool for audio plugins at the moment and am using ACTS for generating test cases at the moment. However since i'm working in a C++ domain, its quite cumbersome to integrate with acts. I've found your project and was wondering what the status of the project is?
I've read in the description that it is experimental, but is the basic functionality (without constraints) ready to use, and if so, how does it compare to acts?
Thanks a lot, Stephan

**Comment by jesg** [comment]
> I've found your project and was wondering what the status of the project is?

i am not working on the project anymore.  with that said i'm happy to accept pull requests that are backwards compatible and pass the unit tests.

> I've read in the description that it is experimental, but is the basic functionality (without constraints) ready to use, and if so, how does it compare to acts?

dither-cxx implements ipog with some basic constraint handling.  it looks like acts implements ipog-c[[0](https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=913191)] which is probably more efficient.

it is used as a backend in [dither](https://github.com/jesg/dither).

[dither_test.cc](https://github.com/jesg/dither-cxx/blob/master/tests/dither_test.cc) should provide some examples.  the interface isn't very nice.  you would need a layer to translate between your test input and numerical values that dither-cxx understands.

**Comment by stephanvalentan** [comment]
Nice! I'll probably file some small PRs if i encounter any issues :)
