### ISSUE TITLE
Make use of gecode optional if no constraint handling is necessary

### ISSUE THREAD

**Issue by vallant** [jesg/dither-cxx#3]
Hi, what do you think of adding a cmake-parameter that handles whether gecode and the simple_constraint_handler should be used? 
In my specific case i dont need constraint handling, but it would add quite much to the compile times.
In the default case i'd leave it on, of course, but in case gecode shouldn't be used, i'd just dont compile gecode and the `simple_constraint_handler.cc`. 
Best, Stephan

Actually, is gecode even used in the project, or is it just the self-written `simple_constraint_handler.cc`? In that case i'd just completely remove all references to gecode!

**Comment by jesg** [comment]
> Actually, is gecode even used in the project, or is it just the self-written simple_constraint_handler.cc?

only simple_constraint_handler.cc is used.

> In that case i'd just completely remove all references to gecode!

sounds good to me
